import { createAnimations } from '@tamagui/animations-react-native';
import { createFont, createTamagui, createTokens } from '@tamagui/core';

// 기본 폰트 설정
const bodyFont = createFont({
  family: 'Pretendard',
  size: {
    1: 12,
    2: 14,
    3: 15,
    4: 16,
    5: 18,
    6: 20,
    6.5: 22,
    7: 24,
    8: 28,
    9: 32,
    10: 40,
    11: 44,
    12: 48,
    true: 16,
  },
  lineHeight: {
    1: 17,
    2: 20,
    3: 21,
    4: 22,
    5: 25,
    6: 28,
    7: 32,
    8: 36,
    9: 40,
    10: 52,
    true: 22,
  },
  weight: {
    3: '300',
    4: '400',
    5: '500',
    6: '600',
    7: '700',
  },
  face: {
    400: { normal: 'Pretendard-Regular' },
    500: { normal: 'Pretendard-Medium' },
    600: { normal: 'Pretendard-SemiBold' },
    700: { normal: 'Pretendard-Bold' },
  },
  letterSpacing: {
    4: 0,
    5: 0,
    6: -0.5,
    7: -1,
  },
});

// 원본 CSS 변수를 Tamagui 토큰으로 변환
const tokens = createTokens({
  color: {
    background: '#F6F3EE',
    foreground: '#30221B',
    card: '#ffffff',
    cardPress: 'rgba(245, 239, 224, 0.25)',
    muted: '#F5EFE0',
    mutedPress: '#E8D5B7',
    mutedStrong: '#E8D5B7',
    mutedForeground: '#5C4A36',
    accent: '#C8DEE6',
    accentPress: '#B8CED6',
    accentStrong: '#9BC4D1',
    destructive: '#E89B8F',
    destructiveText: '#B0503F',
    destructiveForeground: '#ffffff',
    placeholderForeground: '#8B7355',
    border: 'rgba(155, 196, 209, 0.25)',
  },
  space: {
    0: 0,
    0.5: 2,
    1: 4,
    1.5: 6,
    2: 8,
    2.5: 10,
    3: 12,
    3.5: 14,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    11: 44,
    12: 48,
    14: 56,
    16: 64,
    20: 80,
    24: 96,
    28: 112,
    32: 128,
    true: 16,
  },
  size: {
    0: 0,
    0.5: 2,
    1: 4,
    1.5: 6,
    2: 8,
    2.5: 10,
    3: 12,
    3.5: 14,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    11: 44,
    12: 48,
    14: 56,
    16: 64,
    20: 80,
    true: 16,
  },
  radius: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    true: 20,
  },
  zIndex: {
    0: 0,
    1: 100,
    2: 200,
    3: 300,
    4: 400,
    5: 500,
  },
});

const animations = createAnimations({
  fast: {
    type: 'spring',
    damping: 20,
    mass: 1.2,
    stiffness: 250,
  },
  medium: {
    type: 'spring',
    damping: 15,
    mass: 1,
    stiffness: 150,
  },
  slow: {
    type: 'spring',
    damping: 20,
    stiffness: 60,
  },
  pressed: {
    type: 'timing',
    duration: 1500,
  },
  lazy: {
    type: 'timing',
    duration: 200,
  },
  slowReturn: {
    damping: 60, // 높을수록 진동 없이 부드럽게 감속
    mass: 1,
    stiffness: 40, // 낮을수록 느리게 복귀
  },
});

export const config = createTamagui({
  tokens,
  fonts: {
    body: bodyFont,
    heading: bodyFont,
  },
  themes: {
    light: {
      // background: tokens.color.background,
      // backgroundHover: tokens.color.muted,
      // cardPress: tokens.color.muted,
      // backgroundFocus: tokens.color.muted,
      // color: tokens.color.foreground,
      // colorHover: tokens.color.foreground,
      // colorPress: tokens.color.foreground,
      // colorFocus: tokens.color.foreground,
      // borderColor: tokens.color.border,
      // borderColorHover: tokens.color.primary,
      // borderColorFocus: tokens.color.primary,
      // borderColorPress: tokens.color.primary,
      // placeholderColor: tokens.color.placeholderForeground,
      // // 커스텀 테마 값
      // card: tokens.color.card,
      // primary: tokens.color.primary,
      // secondary: tokens.color.secondary,
      // muted: tokens.color.muted,
      // mutedForeground: tokens.color.mutedForeground,
      // accent: tokens.color.accent,
      // accentForeground: tokens.color.accentForeground,
      // destructive: tokens.color.destructive,
      // destructiveForeground: tokens.color.destructiveForeground,
      // inputBackground: tokens.color.inputBackground,
      // foreground: tokens.color.foreground,
      // // 호버/프레스 색상
      // accentPress: tokens.color.accentPress,
      // cardPress: tokens.color.cardPress,
    },
  },
  animations,
  shorthands: {
    // 자주 사용하는 스타일 단축키
    bg: 'backgroundColor',
    p: 'padding',
    pt: 'paddingTop',
    pb: 'paddingBottom',
    pl: 'paddingLeft',
    pr: 'paddingRight',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    m: 'margin',
    mt: 'marginTop',
    mb: 'marginBottom',
    ml: 'marginLeft',
    mr: 'marginRight',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    w: 'width',
    h: 'height',
    br: 'borderRadius',
    bw: 'borderWidth',
    bc: 'borderColor',
    f: 'flex',
    ai: 'alignItems',
    jc: 'justifyContent',
    fd: 'flexDirection',
    fw: 'flexWrap',
    fg: 'flexGrow',
    fs: 'flexShrink',
    fb: 'flexBasis',
  } as const,
});

export type AppConfig = typeof config;

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;
