import { createTamagui, createTokens, createFont } from '@tamagui/core'
import { createAnimations } from '@tamagui/animations-react-native'

// 기본 폰트 설정
const bodyFont = createFont({
  family: 'System',
  size: {
    1: 12,
    2: 14,
    3: 15,
    4: 16,
    5: 18,
    6: 20,
    7: 24,
    8: 28,
    9: 32,
    10: 40,
    true: 16,
  },
  lineHeight: {
    1: 17,
    2: 20,
    3: 21,
    4: 22,
    5: 25,
    6: 28,
    7: 32,
    8: 36,
    9: 40,
    10: 52,
    true: 22,
  },
  weight: {
    4: '400',
    5: '500',
    6: '600',
    7: '700',
  },
  letterSpacing: {
    4: 0,
    5: 0,
    6: -0.5,
    7: -1,
  },
})

// 원본 CSS 변수를 Tamagui 토큰으로 변환
const tokens = createTokens({
  color: {
    // 라이트 테마 색상 (globals.css에서 가져옴)
    background: '#EDF6F9',
    foreground: '#5C4033',
    card: '#FFFBF0',
    cardForeground: '#5C4033',
    popover: '#FFFBF0',
    popoverForeground: '#5C4033',
    primary: '#9BC4D1',
    primaryForeground: '#ffffff',
    secondary: '#E8D5B7',
    secondaryForeground: '#5C4033',
    muted: '#F5EFE0',
    mutedForeground: '#8B7355',
    accent: '#C8DEE6',
    accentForeground: '#5C4033',
    destructive: '#E89B8F',
    destructiveForeground: '#ffffff',
    border: 'rgba(155, 196, 209, 0.25)',
    input: 'transparent',
    inputBackground: '#FFF8E7',
    switchBackground: '#C8DEE6',
    ring: '#9BC4D1',
    // 차트 색상
    chart1: '#9BC4D1',
    chart2: '#E8D5B7',
    chart3: '#C8E4C1',
    chart4: '#F5D5A8',
    chart5: '#D5B8E8',
    // 추가 색상
    white: '#ffffff',
    black: '#000000',
    transparent: 'transparent',
    // 호버/프레스 색상
    accentHover: '#B8CED6',
    primaryHover: '#88B3C3',
    secondaryHover: '#D5C5A8',
    destructiveHover: '#D88B7F',
  },
  space: {
    0: 0,
    0.5: 2,
    1: 4,
    1.5: 6,
    2: 8,
    2.5: 10,
    3: 12,
    3.5: 14,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    11: 44,
    12: 48,
    14: 56,
    16: 64,
    20: 80,
    24: 96,
    28: 112,
    32: 128,
    true: 16,
  },
  size: {
    0: 0,
    0.5: 2,
    1: 4,
    1.5: 6,
    2: 8,
    2.5: 10,
    3: 12,
    3.5: 14,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    11: 44,
    12: 48,
    14: 56,
    16: 64,
    20: 80,
    true: 16,
  },
  radius: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    true: 20,
  },
  zIndex: {
    0: 0,
    1: 100,
    2: 200,
    3: 300,
    4: 400,
    5: 500,
  },
})

const animations = createAnimations({
  fast: {
    type: 'spring',
    damping: 20,
    mass: 1.2,
    stiffness: 250,
  },
  medium: {
    type: 'spring',
    damping: 15,
    mass: 1,
    stiffness: 150,
  },
  slow: {
    type: 'spring',
    damping: 20,
    stiffness: 60,
  },
})

export const config = createTamagui({
  tokens,
  fonts: {
    body: bodyFont,
    heading: bodyFont,
  },
  themes: {
    light: {
      background: tokens.color.background,
      backgroundHover: tokens.color.muted,
      backgroundPress: tokens.color.muted,
      backgroundFocus: tokens.color.muted,
      color: tokens.color.foreground,
      colorHover: tokens.color.foreground,
      colorPress: tokens.color.foreground,
      colorFocus: tokens.color.foreground,
      borderColor: tokens.color.border,
      borderColorHover: tokens.color.primary,
      borderColorFocus: tokens.color.primary,
      borderColorPress: tokens.color.primary,
      placeholderColor: tokens.color.mutedForeground,
      // 커스텀 테마 값
      card: tokens.color.card,
      cardForeground: tokens.color.cardForeground,
      primary: tokens.color.primary,
      primaryForeground: tokens.color.primaryForeground,
      secondary: tokens.color.secondary,
      secondaryForeground: tokens.color.secondaryForeground,
      muted: tokens.color.muted,
      mutedForeground: tokens.color.mutedForeground,
      accent: tokens.color.accent,
      accentForeground: tokens.color.accentForeground,
      destructive: tokens.color.destructive,
      destructiveForeground: tokens.color.destructiveForeground,
      ring: tokens.color.ring,
      inputBackground: tokens.color.inputBackground,
      // 차트 색상
      chart1: tokens.color.chart1,
      chart2: tokens.color.chart2,
      chart3: tokens.color.chart3,
      chart4: tokens.color.chart4,
      chart5: tokens.color.chart5,
      // 호버/프레스 색상
      accentHover: tokens.color.accentHover,
      primaryHover: tokens.color.primaryHover,
    },
  },
  animations,
  shorthands: {
    // 자주 사용하는 스타일 단축키
    bg: 'backgroundColor',
    p: 'padding',
    pt: 'paddingTop',
    pb: 'paddingBottom',
    pl: 'paddingLeft',
    pr: 'paddingRight',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    m: 'margin',
    mt: 'marginTop',
    mb: 'marginBottom',
    ml: 'marginLeft',
    mr: 'marginRight',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    w: 'width',
    h: 'height',
    br: 'borderRadius',
    bw: 'borderWidth',
    bc: 'borderColor',
    f: 'flex',
    ai: 'alignItems',
    jc: 'justifyContent',
    fd: 'flexDirection',
    fw: 'flexWrap',
    fg: 'flexGrow',
    fs: 'flexShrink',
    fb: 'flexBasis',
  } as const,
})

export type AppConfig = typeof config

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config
